version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
    ports:
      - "3306:3306"
  sftp:
    image: atmoz/sftp
    volumes:
      - /gradle/:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001